# Generated by Django 5.1.3 on 2024-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_booking_vehicle_id_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_capacity', models.IntegerField()),
                ('remaining_capacity', models.IntegerField()),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'garages',
            },
        ),
    ]
